// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewUser struct {
	IsAdmin  bool   `json:"is_admin"`
	Name     string `json:"name"`
	Password string `json:"password"`
	Email    string `json:"email"`
	IsAble   bool   `json:"is_able"`
}

type NewWork struct {
	Title          string  `json:"title"`
	Summary        *string `json:"summary"`
	ImageURL       *string `json:"image_url"`
	Duration       *string `json:"duration"`
	NumberOfPeople *int    `json:"number_of_people"`
	Language       *string `json:"language"`
	Role           *string `json:"role"`
	URL            string  `json:"url"`
	BriefStory     *string `json:"brief_story"`
}

type User struct {
	ID       string `json:"id"`
	IsAdmin  bool   `json:"is_admin"`
	Name     string `json:"name"`
	Password string `json:"password"`
	Email    string `json:"email"`
	IsAble   bool   `json:"is_able"`
}

type Work struct {
	ID             string  `json:"id"`
	Title          string  `json:"title"`
	Summary        *string `json:"summary"`
	ImageURL       *string `json:"image_url"`
	Duration       *string `json:"duration"`
	NumberOfPeople *int    `json:"number_of_people"`
	Language       *string `json:"language"`
	Role           *string `json:"role"`
	URL            string  `json:"url"`
	BriefStory     *string `json:"brief_story"`
}
